version: '3'
services:
  api:
    image: node:13.6
    network_mode: 'bridge'
    env_file:
      - config.env
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://docker.for.mac.localhost:27017/
    volumes:
      - ./:/code/
    ports:
      - '8001:8001'
    command: bash -c "cd /code && npm install && npm run dev"
