version: '3'
services:
  api:
    image: node:13.6
    network_mode: "host"
    env_file:
      - config.env
    environment:
      - NODE_ENV=development
    volumes:
      # - ./node_modules/:/node_modules/
      # - ./package.json:/package.json
      # - ./package-lock.json:/package-lock.json
      # - ./.babelrc:/.babelrc
      # - ./config.env:/config.env
      # - ./src/index.js:/index.js
      # - ./src/logger.js:/logger.js
      - ./:/code/
    ports:
      - "8001:8001"
    command: bash -c "cd /code && npm run start"
  database:
    image: mongo:4.0.14
    network_mode: "host"
    environment:
      - MONGO_INITDB_DATABASE=calendar-api
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=password
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./db:/data/db
