version: '3'
services:
  api:
    image: node:12
    container_name: api
    build: .
    network_mode: "host"
    env_file:
      - .env
      - config.env
    environment:
      - PORT=8001
      - NODE_ENV=production
    volumes:
      - ./node_modules/:/node_modules/
      - ./package.json:/package.json
      - ./package-lock.json:/package-lock.json
      - ./.env:/.env
      - ./config.env:/config.env
      - ./dist/:/dist
    ports:
      - "8001:8001"
    command: bash -c "npm install && npm run prod:start"
